# Generated by Django 2.0.3 on 2018-03-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180323_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='网站分类名')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSubCategory',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='网站子分类名')),
                ('siteCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.SiteCategory')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
